### ISSUE TITLE
Java 11 compatibility when using docker-minecraft-server

### ISSUE THREAD

**Issue by benab** [GeyserMC/Floodgate#120]
Hello. I just discovered Floodgate a few days ago! I'm excited such a thing exists.

My problem is that I haven't had any luck running a Paper server with the **floodgate-bukkit** plugin in the _latest_ Java version in [docker-minecraft-server](https://github.com/itzg/docker-minecraft-server).
Each time I copy floodgate-bukkit.jar to the plugins folder and start the server, it results in a Java crash. [See logs here: https://controlc.com/32c1b62](https://controlc.com/32c1b624)

For testing I start with an empty /data folder. I start with no plugins, then add Geyser-Spigot.jar, restart the server (no crash), add floodgate-bukkit.jar, restart and get a Java crash as posted above.
The following Java tags all crash: **latest** (Java 11), **openj9-11** (Java 11), **java15** (Java 15).

I have gotten the **java8** (Java 8) tag to work without crashing.

Here is a general docker-compose I run.
version: "3"

```
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-paper-creative
    ports:
      - 25100:25565
      - 19100:19132/udp
    environment:
      EULA: "TRUE"
      MOTD: "Welcome to my creative castle"
      ICON: file:///data/icon.png
      OVERRIDE_ICON: "TRUE"
      MODE: creative
      TYPE: "PAPER"
    volumes:
      - ./data:/data
    restart: unless-stopped
```
  

Am I doing something incorrectly?  I also wonder if this is an issue with the Docker version of Minecraft rather than a Floodgate issue. Any guidance is welcome. Thanks!

**Comment by LichLord91** [comment]
Hey Benab,

I use ITZG's docker as well on a pi4 with java 15 and on arm64 and have no troubles with geyser/floodgate. (make sure your docker and docker-compose it up to date)

I think if you add some of these environment variables it may help. 

I noticed in you log you're only using basic jvm arguments. 

"Command Line: -XX:+UseG1GC -Xms1G -Xmx1G paper-1.16.5-508.jar"  

its highly recommend to use Aikar's suggested jvm arguments which can be added automatically by the environment variable **USE_AIKAR_FLAGS: "true"** more info here>
 [aikar's website](https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/) and [itzg-doc](https://github.com/itzg/docker-minecraft-server#enable-aikars-flags)

I'd also bump up the server memory to at least 2gb  by adding this environment variable **MEMORY: "2G"** [itzg-doc](https://github.com/itzg/docker-minecraft-server#memory-limit)

So here's what your config should look like

```
version: "3"

services:
minecraft:
image: itzg/minecraft-server
container_name: mc-paper-creative
ports:
- 25100:25565
- 19100:19132/udp
environment:
EULA: "TRUE"
MOTD: "Welcome to my creative castle"
ICON: file:///data/icon.png
OVERRIDE_ICON: "TRUE"
MODE: creative
TYPE: "PAPER"
USE_AIKAR_FLAGS: "true"
MEMORY: "2G"
volumes:
- ./data:/data
restart: unless-stopped

```


Try these settings out and see if that helps.

**Comment by benab** [comment]
LichLord91,
Thanks much for the tips! I added the Aikar flags and the memory variables that you noted.

That didn't help the Java crashes, so I checked the Docker versions. I was running:
-Docker version 20.10.4, build d3cb89e
-docker-compose version 1.23.2, build 1110ad01

It seemed that Docker Compose was very out of date. (Apt had not been managing it!)
I updated Docker Compose to the latest: docker-compose version 1.28.5, build c4eb3a1f

I am still getting the Java crashes. (a boot loop) :(
I'm not sure what else to do other than use Java8 or build a test VM from scratch to see if the issue reproduces itself. 

Thanks again for taking the time to assist!

**Comment by LichLord91** [comment]
Hey behab ,

You dont want to run java 8 it's starting to get depreciated for all minecraft related stuff. You said you had this crash on each different java version you tried? When you added aikar's flags did you get a different crash or at least a more detailed report? i believe it may add more detail with those flags.

Otherwise here a  break down of or error and what might fix it. This may be an upstream issue with ITZG's docker container and you may want to report it. Mine uses Ubuntu since i use the multi-arch build and yours uses Alpine which is why you may be getting errors while i am not. 

This also could be hardware related but i think its more on the library side of things

![image](https://user-images.githubusercontent.com/8435580/109758396-5bcbd180-7ba0-11eb-97b0-260748927fc7.png)


here is a tool i used for the JAVA GC dump analytics

https://gceasy.io/hs-report.jsp?p=YXJjaGl2ZWQvMjAyMS8wMy8zLy0tYXBpLWNjMDc1YjNiLTA3NTktNDA1OC04NmRjLWNlNTVkMjk5ZGFhMDBmYjQ4OWRjLWVhNzctNGY5Zi1hNWQ5LWFkYWE3NWFkNmIxMi50eHQ=&channel=API#crash


Doing a quick google search i see that that this might help.

https://stackoverflow.com/questions/55714251/openjdk-11-on-busybox-crash-on-sigsegv-in-libc-so

You may also try to run the multi-arch build which is based on ubuntu instead.

 itzg/minecraft-server:2021.6.0-multiarch-latest for java 15
 
 itzg/minecraft-server:2021.6.0-multiarch for java 11

**Comment by Camotoy** [comment]
Heyo,

In your crash report under Internal Exceptions, it points to a NoSuchMethod error being the culprit (perhaps an SQL Lite error?). Unfortunately this error doesn't tell us *what* method is non-existent - do you have normal Minecraft server logs as well?

**Comment by benab** [comment]
@LichLord91 

Yeah! Ubuntu did it! It doesn't matter to me whether I use Ubuntu or Alpine in the image, whatever works!

> Otherwise here a break down of the error and what might fix it. This may be an upstream issue with ITZG's docker container and you may want to report it. Mine uses Ubuntu since i use the multi-arch build and yours uses Alpine which is why you may be getting errors while i am not.
> 
Given that the Ubuntu image works, does it appear that it is an issue with ITZG's Alpine docker container?

> You may also try to run the multi-arch build which is based on ubuntu instead.
> 
> itzg/minecraft-server:2021.6.0-multiarch-latest for java 15
> 
> itzg/minecraft-server:2021.6.0-multiarch for java 11

Using the _itzg/minecraft-server:2021.6.0-multiarch_  image worked for me! (see my docker-compose below)

```
version: "3"
services:
  minecraft:
    image: itzg/minecraft-server:2021.6.0-multiarch
    container_name: mc-paper-creative2
    ports:
      - 25100:25565
      - 19100:19132/udp
    environment:
      EULA: "TRUE"
      OVERRIDE_ICON: "TRUE"
      MODE: creative
      TYPE: "PAPER"
      USE_AIKAR_FLAGS: "true"
      MEMORY: "2G"
    volumes:
      - ./data2:/data
    restart: unless-stopped

```
Thanks again!
